[package]
name = "ndpi-sys"
version = "5.0.0"
edition = "2024"
description = "Rust -sys bindings for nDPI 5.0 (git submodule source)"
license = "LGPL-3.0-only"
readme = "README.md"
links = "ndpi"
build = "build.rs"

[build-dependencies]
cc = "1.2"
walkdir = "2.5"
